# Generated by Django 4.2.14 on 2025-05-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
