# Generated by Django 4.2.14 on 2025-09-09 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_filemodel_shares_with"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemodel",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
