# Generated by Django 4.2.14 on 2025-09-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_filemodel_created_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filemodel",
            options={"ordering": ["-created_date"]},
        ),
    ]
