# Generated by Django 4.2.14 on 2025-05-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='storage_capacity',
            field=models.IntegerField(default=2000),
        ),
    ]
