# Generated by Django 4.2.14 on 2025-05-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_storage_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='storage_capacity',
            field=models.BigIntegerField(default=2147483648),
        ),
    ]
