# Generated by Django 4.2.14 on 2025-09-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_storage_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="storage_capacity",
            field=models.BigIntegerField(default=209715200),
        ),
    ]
